stack:
  name:
  account:
  region:

githubRepoOwner:
githubRepoName:
githubAccessTokenName:

# set deploy to 'true' if you want to enable deplyment of environment [development 0r production]
# one can be 'true' at a time
development:
  deploy: true
  environmentType: dev
  branchName: dev-branch
  pipelineConfig:
    name: dev-pipeline
  s3Config:
    bucketName: dev-bucket
    artifactsBucket: dev-artifacts-bucket
    publicAccess: true
    indexFile: index-dev.html
    errorFile: error-dev.html

production:
  deploy: false
  environmentType: prod
  branchName: prod-branch
  pipelineConfig:
    name: prod-pipeline
  s3Config:
    bucketName: prod-bucket
    artifactsBucket: prod-artifacts-bucket
    publicAccess: false
    indexFile: index-prod.html
    errorFile: error-prod.html
