stack:
  name:
  account:
  region:

githubRepoOwner:
githubRepoName:

dev:
  deploy: true
  environmentType: dev
  branchName: dev
  pipelineConfig:
    name: project-dev
  s3Config:
    bucketName: project-dev-bucket
    publicAccess: true
    indexFile: index.html
    errorFile: index.html

prod:
  deploy: false
  environmentType: prod
  branchName: main
  pipelineConfig:
    name: project-prod
  s3Config:
    bucketName: project-prod-bucket
    publicAccess: true
    indexFile: index.html
    errorFile: index.html
